Start Menu screen created
Luisill0/Proyecto-Greenfoot pull request #5
Opened 2021-05-27 01:46 UTC by Luisill0

2021-06-01 13:17 UTC, J-Orta submitted a review, later dismissed

2021-06-01 15:45 UTC, iuresti requested changes

2021-06-01 15:45 UTC, iuresti commented on StartMenu.java
> +public class StartMenu extends Game
¿"StartMenu" es un "Game"? eso estás diciendo con tu jerarquía de clases

2021-06-01 15:45 UTC, iuresti commented on Button.java
> +    public String getMessage(){
Si el message es solo para uso interno de esta clase, no es obligatorio que proveas un getter para el atributo

2021-06-01 15:45 UTC, iuresti commented on Controls.java
> +public class Controls extends StartMenu
¿"Controls" es un "StartMenu"? ... Eso dice tu jerarquía de clases.

Veo que intentas reusar el mundo, no es neceasario, al contrario te añade complejidad innecesaria al programa. Crea un World por cada pantalla que requieras

2021-06-01 15:45 UTC, iuresti commented on Game.java
> +        Greenfoot.setWorld(new StartMenu());
El método act se ejecuta varias veces por segundo.. aquí estás creando objetos "StartMenu" por siempre.. te puede dar un problema de memoria y seguro tampoco actuará como deseas

2021-06-01 15:45 UTC, iuresti commented on HighScores.java
> +        this.addObject(new Text("High Scores",30),300,100);
Mismos comentarios que para Controls

2021-06-01 15:45 UTC, iuresti commented on StartMenu.java
> +        List<Button> buttons = this.getObjects(Button.class);
Recuerda que esto está siendo ejecutado varias veces por segundo

2021-06-01 15:45 UTC, iuresti commented on StartMenu.java
> +                Greenfoot.setWorld(new HighScores());
Delega las acciones a los botones

2021-06-01 15:45 UTC, iuresti commented on Text.java
> +public class Text extends Actor
¿Qué representa "Text" por qué es un "Actor" ?

2021-06-02 19:06 UTC, Luisill0 commented on Text.java
> +public class Text extends Actor
Estaba buscando en foros y al parecer la forma más sencilla de mostrar texto en pantalla es teniendo una clase y hacer que su imagen sea el texto que se quiere mostrar.

Hereda de Actor para que se pueda mostrar en pantalla.

Le cambié el nombre a TextDisplayer para que sea más fácil de entender su función.

2021-06-03 04:25 UTC, iuresti requested changes

2021-06-03 04:25 UTC, iuresti commented on StartMenu.java
> +        this.addObject(new StartMenuButton("New Game",35,1), 300, 130);
Entiendo que proporcionan el id para que el objeto botón sepa a dónde dirigir al darle click, pero esto no es un buen diseño.. están dándole la responsabilidad de cada flujo al StartMenuButton, si necesitan añadir otro flujo siempre tendrán que modificar el StartMenuButton lo que rompe el Open Close Principle .. Creen una clase por cada acción mejor

2021-06-03 04:25 UTC, iuresti commented on ReturnButton.java
> +        this.previous = previous;
Buena idea pasarle el previous.. de ese modo desacoplas el "StartMenu" con el "ReturnButton" y es más flexible

2021-06-06 00:25 UTC, iuresti commented on ExitButton.java
> +    protected void changeScreen()
Ya que no estás cambiando de pantalla el nombre del método es confuso,

2021-06-06 00:26 UTC, iuresti approved these changes

2021-06-06 19:55 UTC, merged